// Initially empty 2D array of 9 rows and 9 columns
let to_verify = [[], [], [], [], [], []];

// This function iterates through the input array and assigns it to to_verify
const arrayPopulatorFunction = (inputArray) => {
  for (let i = 0; i < inputArray.length; i++) {
    to_verify[i] = inputArray[i];
  }
};

// This function will create a table and populate it with the content of to_verify
const tablePopulatorFunction = () => {
  let table = "<p>Table to check :</p><table>";
  // The first for loop goes through to_verify adding the rows to the table
  for (let i = 0; i < to_verify.length; i++) {
    table += "<tr>";
    // The second for loop goes through each column in the current row, adding the new cells to the table with the value of to_verify
    for (let j = 0; j < to_verify[i].length; j++) {
      table += `<td> ${to_verify[i][j]} </td>`;
    }
    table += "</tr>";
  }
  table += "</table>";
  return table;
};

arrayPopulatorFunction(array_number);
// This sets the table generated by the tablePopulatorFunction() as the content of the HTML body
document.body.innerHTML = tablePopulatorFunction();
